version: '3.9'
services:
  svelte-commerce:
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      # Add this line to use .env instead of .env.example
      - ENV_FILE=.env
    pull_policy: always